// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAs9oWt1r6f_FxyC-IeAs_0ye4XQZdbsok',
    appId: '1:687257829326:web:9a481c3adf4f275e47759f',
    messagingSenderId: '687257829326',
    projectId: 'survey-83712',
    authDomain: 'survey-83712.firebaseapp.com',
    storageBucket: 'survey-83712.appspot.com',
    measurementId: 'G-H3S0HP8T7C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASzOXCuncNL9BMP-8-K7-vsZrXs8C95LE',
    appId: '1:687257829326:android:9afc4d104bf3821d47759f',
    messagingSenderId: '687257829326',
    projectId: 'survey-83712',
    storageBucket: 'survey-83712.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCGIFR--G0kkaXOf8Wh8RjBeZMZNpXq2_0',
    appId: '1:687257829326:ios:f1090b8b819b3b8c47759f',
    messagingSenderId: '687257829326',
    projectId: 'survey-83712',
    storageBucket: 'survey-83712.appspot.com',
    iosBundleId: 'com.example.feedbackapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCGIFR--G0kkaXOf8Wh8RjBeZMZNpXq2_0',
    appId: '1:687257829326:ios:c1ac1e676a0653c947759f',
    messagingSenderId: '687257829326',
    projectId: 'survey-83712',
    storageBucket: 'survey-83712.appspot.com',
    iosBundleId: 'com.example.feedbackapp.RunnerTests',
  );
}
