// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBNMFL0imq0H4VvPT0eN1UZCw6LAhAMvKI',
    appId: '1:72455098160:web:f99d3462540e46d82042f5',
    messagingSenderId: '72455098160',
    projectId: 'feedbackapp-5e826',
    authDomain: 'feedbackapp-5e826.firebaseapp.com',
    storageBucket: 'feedbackapp-5e826.appspot.com',
    measurementId: 'G-FLDDNKNWBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD0y3fOsPiMG4kyTTwg96XnqEPMu6QeuRg',
    appId: '1:72455098160:android:4eb872934a8d59dd2042f5',
    messagingSenderId: '72455098160',
    projectId: 'feedbackapp-5e826',
    storageBucket: 'feedbackapp-5e826.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDTfLUlgE12ooJG62cuZGuWwbabKJhPnlc',
    appId: '1:72455098160:ios:d40b1a48b49aa9642042f5',
    messagingSenderId: '72455098160',
    projectId: 'feedbackapp-5e826',
    storageBucket: 'feedbackapp-5e826.appspot.com',
    iosBundleId: 'com.example.feedbackapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDTfLUlgE12ooJG62cuZGuWwbabKJhPnlc',
    appId: '1:72455098160:ios:eb4f5e3873a485c42042f5',
    messagingSenderId: '72455098160',
    projectId: 'feedbackapp-5e826',
    storageBucket: 'feedbackapp-5e826.appspot.com',
    iosBundleId: 'com.example.feedbackapp.RunnerTests',
  );
}
